apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-acm-policies
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: acm-manifests/policies
    repoURL: https://github.com/ngner/argocd-rhacm.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
