apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-acm-policies
  namespace: openshift-gitops
spec:
  destination:
    namespace: rhacm-policies
    server: https://kubernetes.default.svc
  project: rhacm-policies
  source:
    path: acm-manifests/policies
    repoURL: https://github.com/ngner/argocd-rhacm.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true

# Note we need to tell ArgoCD to ignore the rhacm-policies rendered by ACM otherwise ArgoCD thinks they should be pruned when syncing. 
# To do this we need a seperate ArgoCD project 

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rhacm-policies
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'rhacm-policies'
    name: 'local-cluster-acm-policies'
    server: '*'
  sourceRepos:
  - '*'
