apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  namespace: gitops-test
data:
  # property-like keys; each key maps to a simple value
  how_good_is_OCP: great

  # file-like keys
  something_about_text: |
    lots of interesting text 
    on several lines of ig_unit_information:
    client:  # not required. A dict object containing connection details.   


--- 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: gitops-test
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: foo_bar
    remoteRef:
      key: /foo/bar
      version: v1
  dataFrom:
  - extract:
      key: /foo/baz