
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-root-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops-root-applications
    repoURL: https://github.com/ngner/argocd-rhacm.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
