# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: openshift-gitops

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - openshift-gitops-instance.yaml
  - gitops-root-app.yaml
