
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceCustomizations: |
    bitnami.com/SealedSecret:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Controller doesnt report resource status"
        return hs
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /spec/host
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  applicationSet:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "1"
        memory: 2Gi
    sharding:
      enabled: true
      replicas: 3
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  kustomizeBuildOptions: --enable-alpha-plugins
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    env:
    - name: ARGOCD_EXEC_TIMEOUT
      value: 360s
    - name: KUSTOMIZE_PLUGIN_HOME
      value: /.config/kustomize/plugin
    initContainers:
    - args:
      - /.config
      command:
      - /exportkustomize.sh
      image: "registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.16"
      imagePullPolicy: Always
      name: kustomize-plugin
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /.config
        name: kustomize
    - args:
        - -c
        - mkdir -p /.config/kustomize/plugin/ && cp -r /etc/kustomize/plugin/policy.open-cluster-management.io /.config/kustomize/plugin/
      command:
        - /bin/bash
      image: "registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel8:v2.9.4-16"
      name: policy-generator-install
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /.config
          name: kustomize
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
      requests:
        cpu: "1"
        memory: 2Gi
    volumeMounts:
    - mountPath: /.config
      name: kustomize
    volumes:
    - name: kustomize
      # readOnly: false
      # path: ./config
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ""
  sso:
    dex:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      openShiftOAuth: true
    provider: dex
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, ocpadmin, role:admin
    scopes: '[groups]'
  tls:
    ca: {}
--- 
apiVersion: v1
kind: Secret
metadata:
  name: acm-git-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ngner/argocd-rhacm.git