---
### DO NOT COMMIT THIS WITH THE TOKEN IN !!!!

# Copy from the README then save then delete the file straight after so it doesn't accidentally get committed to the repo.

apiVersion: v1
kind: Secret
metadata:
  name: git-repo-creds
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/ngner/argocd-rhacm.git
  password: ADDME
  username: argocd-rhacm