---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ''
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    # We will use the Default Argo Instance - one can have seperate instances for Local (policy and ACM), Global, Teams etc.
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"

    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: open-cluster-management-global-set, dk8se-gitops-root-sub
    #NOTE: Namespaces from which Applications can be source 
    # Those managed by ArgoCD must have label `argocd.argoproj.io/managed-by=dk8se-gitops-root-sub`
  #startingCSV: openshift-gitops-operator.v1.5.4
---

apiVersion: operators.coreos.com/v1

kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
