---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-service-account
rules:
- apiGroups:
  - open-cluster-management.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - triggers.tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - placementbindings
  - policies
  - policysets
  verbs:
  - '*'
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - placementrules
  verbs:
  - '*'
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  verbs:
  - '*'
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets
  - managedclustersetbindings
  - placements
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  - appprojects
  - applications
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - provisionings
  verbs:
  - '*'
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agentserviceconfigs
  - nmstateconfigs
  verbs:
  - '*'
- apiGroups:
  - ran.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - nmstate.io
  resources:
  - "nodenetworkconfigurationpolicies"
  verbs:
  - '*'
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-service-account
subjects:
- kind: ServiceAccount
  name: gitops-root-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: argocd-cluster-argocd-server
  namespace: openshift-gitops