---
## Allow GitOps to act as Cluster Management Admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-service-account-cluster-manager-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-manager-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops


---
# Allow gitops service account to deploy non-acm resources

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-service-account
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: argocd-cluster-argocd-server
  namespace: openshift-gitops

  
---

#TODO RBAC check....
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-service-account
rules:
## Until MCH is established the buit in roles for ACM don't exist.
- apiGroups:
  - operator.open-cluster-management.io
  - apps.open-cluster-management.io
  - policy.open-cluster-management.io
  - cluster.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - '*'
  
## Enable Argo to manage non ACM resources 
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kafka.strimzi.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - camel.apache.org
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - triggers.tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - external-secrets.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cert-manager.io
  resources:
  - '*'
  verbs:
  - '*'
 


