---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ''
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    # We will use the Default Argo Instance - one can have seperate instances for Local (policy and ACM), Global, Teams etc.
    # - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
    #   value: "true"
    # We want to allow for more than just applicaitons and policies on local cluster.
    # We want to allow for all cluster namespaces to deploy clusters.
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: openshift-gitops,open-cluster-management-global-set
    #NOTE: Namespaces which will be managed by the ArgoCD must be above or have label `argocd.argoproj.io/managed-by=openshift-gitops`
  #startingCSV: openshift-gitops-operator.v1.5.4
---

apiVersion: operators.coreos.com/v1

kind: OperatorGroup
metadata:
  name: openshift-gitops-operator
