# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: openshift-gitops

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: git-repo-creds
  envs:
  - gitsecret.env
  literals:
  - type=git
  - url=https://github.com/ngner/argocd-rhacm.git
  - username=argocd-rhacm
- name: central-vault-key
  envs:
  - central-vault-key-secret.env

patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: git-repo-creds
      labels:
        argocd.argoproj.io/secret-type: repo-creds

# list of Resource Config to be Applied
resources:
  - namespace.yaml
  - gitops-operator.yaml
  - root-app
  # for git-secret use environment variable password={somepassword for git} before running oc apply -k .



