---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-policies
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
### More namespaces here independent of the resources so namespace creation can be kept seperate for RBAC.

