
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: acm-open-cluster-management
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - open-cluster-management

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: release-2.6
  installPlanApproval: Automatic
  name: advanced-cluster-management
