apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline
  name: external-secrets-operator-policy
  namespace: policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-external-secrets-operator-namespace
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: external-secrets-system
                  labels:
                    argocd.argoproj.io/managed-by: openshift-gitops
                spec: {}
              remediationAction: enforce
              severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-external-secrets-operator-operatorconfig
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.external-secrets.io/v1alpha1
                kind: OperatorConfig
                metadata:
                  name: cluster
                  namespace: external-secrets-system
                spec:
                  prometheus:
                    enabled: true
                    service:
                      port: 8080
                  resources:
                    limits:
                      cpu: 100m
                      memory: 256Mi
                    requests:
                      cpu: 10m
                      memory: 96Mi
              remediationAction: enforce
              severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-external-secrets--operator-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  labels:
                    operators.coreos.com/external-secrets-operator.openshift-operators: ""
                  name: external-secrets-operator
                  namespace: openshift-operators
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: external-secrets-operator
                  source: community-operators
                  sourceNamespace: openshift-marketplace
              remediationAction: enforce
              severity: high
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-external-secrets-operator-policy
  namespace: policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-external-secrets-operator-policy
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: external-secrets-operator-policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-external-secrets-operator-policy
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable

