apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-of-vaults-secretstore
spec:
  provider:
    vault:
      auth:
        appRole:
          path: central-vault
          roleId: fromSecret-central-vault-key # To be replaced with reference to secret
          secretRef:
            key: secret-id
            name: central-vault-key
      path: central-vault
      server: https://localhost
      version: v2