---
## This fake is stub example provide for testing provided ESO
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/foo/bar"
        value: "HELLO1"
        version: "v1"
      - key: "/foo/bar"
        value: "HELLO2"
        version: "v2"
      - key: "/foo/baz"
        valueMap:
          foo: example
          other: thing
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-of-vaults-secretstore
spec:
  provider:
    vault:
      auth:
        appRole:
          path: central-vault
          roleId: fromSecret-central-vault-key # To be replaced with reference to secret
          secretRef:
            key: secret-id
            name: central-vault-key
      path: central-vault
      server: https://localhost
      version: v2

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-example
  namespace: external-secrets-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  data:
  - secretKey: foo_bar
    remoteRef:
      key: /foo/bar
      version: v1
  dataFrom:
  - extract:
      key: /foo/baz